trigger:
- main

pool:
  name: 'Default'

variables:
  - group: piano-app-secrets 

stages:
- stage: QA_Automation
  jobs:
  - job: Run_Tests
    steps:
    # 1. Using native powershell for Python
    - powershell: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: '1. Install Flask App Deps'

    # 2. Using native powershell for Playwright
    - powershell: |
        npm install
        npx playwright install --with-deps
      displayName: '2. Install Playwright Deps'

    # 3. Native Start App & Run Tests
    - powershell: |
        $job = Start-Process python -ArgumentList "app.py" -PassThru
        Start-Sleep -Seconds 10
        npx playwright test --reporter=junit,line
      displayName: '3. Run Flask & Playwright TS Tests'
      env:
        DB_PASSWORD: $(DB_PASSWORD)
        PYTHONUTF8: 1
        PLAYWRIGHT_JUNIT_OUTPUT_NAME: results.xml

    # 4. Show the Results
    - task: PublishTestResults@2
      displayName: '4. Publish Test Report'
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: '**/results.xml'
        testRunTitle: 'Playwright TypeScript Report'

- stage: Deploy_Infrastructure
  displayName: 'Deploy to Azure'
  dependsOn: QA_Automation
  condition: succeeded()
  jobs:
  - job: Terraform_Deploy
    steps:
    - powershell: |
        terraform init
        terraform apply -auto-approve
      displayName: 'Terraform Init and Apply'
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)